image:
  repository: fluent/fluent-bit
  tag: 1.9
  pullPolicy: IfNotPresent

config:
  fluentBitConf: |
      [SERVICE]
          Flush        1
          Daemon       Off
          Log_Level    info
          Parsers_File parsers.conf

      [INPUT]
          Name        tail
          Path        /var/log/containers/tenant-log-sim*.log
          Tag         tenant-logs-sim
          Parser      docker
          Mem_Buf_Limit     5MB
          Skip_Long_Lines   On


      [OUTPUT]
          Name        forward
          Match       tenant-logs-sim
          Host        fluentd.logging.svc.cluster.local
          Port        24224

  parsersConf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

resources:
  limits:
    memory: 200Mi
    cpu: 100m
  requests:
    memory: 100Mi
    cpu: 50m

service:
  port: 80
  type: ''

ingress:
  enabled: false