apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluentd.fullname" . }}
  labels:
    app: {{ include "fluentd.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fluentd.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fluentd.name" . }}
    spec:
      containers:
        - name: fluentd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
              readOnly: true
            - name: fluentd-logs
              mountPath: /var/log/fluentd
          ports:
            - containerPort: 24224
      volumes:
        - name: config-volume
          configMap:
            name: '{{ include "fluentd.fullname" . }}-config'
        - name: fluentd-logs
          emptyDir: {}   
     
