apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 24224
      protocol: TCP
  selector:
    app: {{ .Values.name }}
