apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant-python-processor.fullname" . }}
  labels:
    app: {{ include "tenant-python-processor.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tenant-python-processor.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tenant-python-processor.name" . }}
    spec:
      containers:
        - name: tenant-python-processor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}"
            - name: KAFKA_TOPIC
              value: "{{ .Values.env.KAFKA_TOPIC }}"
            - name: POSTGRES_HOST
              value: {{ .Values.postgresql.host }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
              
