replicaCount: 1

fullname: fluentd
name: fluentd
image:
  repository: priyankaguha/fluentd
  pullPolicy: IfNotPresent
  tag: 1.0.0

ingress:
  enabled: false
  hosts:
    - host: fluentd.local
      paths: ["/"]
  annotations: {}
  
service:
  type: ClusterIP
  port: 24224

config:
  fluentdConf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match **>
      @type kafka2
      brokers kafka-0.kafka.logging.svc.cluster.local:9092
      use_event_time true

      <format>
        @type json
      </format>

      # topic settings
        topic_key topic
        default_topic tenant-logs
        partition_key ${record["tenant_id"]}

      
      <buffer>
        @type file
        path /var/log/fluentd/buffer
        flush_interval 5s
        retry_max_times 3
        retry_wait 1s
      </buffer>
      
    </match>

