replicaCount: 1

fullname: fluentd
name: fluentd
image:
  repository: fluent/fluentd
  pullPolicy: IfNotPresent
  tag: v1.14-1

ingress:
  enabled: false
  hosts:
    - host: fluentd.local
      paths: ["/"]
  annotations: {}
  
service:
  type: ClusterIP
  port: 24224

config:
  fluentdConf: |
    <source>
      @type forward
      port 24224
    </source>

    <filter **>
      @type record_transformer
      enable_ruby
      <record>
        enriched_at ${Time.now.to_s}
        env production
      </record>
    </filter>

    <match **>
      @type stdout
    </match>

