apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.zookeeper.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.zookeeper.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.zookeeper.name }}
    spec:
      containers:
        - name: {{ .Values.zookeeper.name }}
          image: {{ .Values.zookeeper.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.zookeeper.service.port }}
              name: client
          env:
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_PORT
              value: "2181"


---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.name }}
spec:
  ports:
    - port: {{ .Values.zookeeper.service.port }}
      targetPort: {{ .Values.zookeeper.service.port }}
      name: client
  selector:
    app: zookeeper
