apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: kafka
  clusterIP: None   # Headless service for StatefulSet
  selector:
    app: kafka