apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.label }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-migration
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgresql.host }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
