apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: logging
data:
  fluent-bit.conf: |-
    {{ .Values.config.fluentBitConf | nindent 4 }}
  parsers.conf: |-
    {{ .Values.config.parsersConf | nindent 4 }}
